### ISSUE TITLE
Tons of build errors, exe missing

### ISSUE THREAD

**Issue by battledash** [mmozeiko/aes-finder#10]
https://imgur.com/a/kYhrmZP

**Comment by battledash** [comment]
not sure if it works at all with vs2017 but I can't find a dl for 2013 ANYWHERE and I took an hour trying to get gcc working but I can't figure out how to get it on windows

**Comment by battledash** [comment]
If I click download for 2013 on the vs download page I get this
https://imgur.com/a/4m4g3Nk

**Comment by mmozeiko** [comment]
> https://imgur.com/a/kYhrmZP

The error says that "v120_xp build tools" cannot be found. That means you are trying to use VS2013 compiler which you dont have. Just change platform toolset in project properties to one you have.

> not sure if it works at all with vs2017 

VS2017 will compile code just fine. Just open solution, VS will automatically upgrade it, and make sure project settings has correct toolset selected.

> but I can't find a dl for 2013 ANYWHERE 

https://www.visualstudio.com/vs/older-downloads/

> and I took an hour trying to get gcc working but I can't figure out how to get it on windows
also fine.

I suggest [MSYS2](https://www.msys2.org/). But alternatives like [this](https://nuwen.net/mingw.html) would also work.

**Comment by battledash** [comment]
Thanks a million I'll try all that rn :D

**Comment by battledash** [comment]
Well I installed vs2013 and and v120_xp build tools and finally got the exe built

but when I run it in an elevated cmd and try it on chrome I get this:
"C:\Users\SirHacksAlot\Videos\aes-finder-master\msvc2013\Debug>aes-finder.exe chrome.exe
Searching PID 20388 ...
Failed to open process
Searching PID 10820 ...
Failed to open process
Searching PID 13780 ...
Failed to open process
Searching PID 18144 ...
Failed to open process
Searching PID 19932 ...
Failed to open process
Searching PID 11276 ...
Failed to open process
Searching PID 3084 ...
Failed to open process
Searching PID 19112 ...
Failed to open process
Searching PID 18028 ...
Failed to open process
Searching PID 18484 ...
Failed to open process
Searching PID 17252 ...
Failed to open process
Searching PID 6244 ...
Failed to open process
Searching PID 23104 ...
Failed to open process
Searching PID 21924 ...
Failed to open process
Done!"

**Comment by battledash** [comment]
same thing with fortnite
"C:\Users\SirHacksAlot\Videos\aes-finder-master\msvc2013\Debug>aes-finder.exe FortniteClient-Win64-Shipping.exe
Searching PID 22156 ...
Failed to open process
Done!"

**Comment by battledash** [comment]
just tried the fortnite battleeye exe FortniteClient-Win64-Shipping_BE.exe and apparently it worked:
"C:\Users\SirHacksAlot\Videos\aes-finder-master\msvc2013\Debug>aes-finder.exe FortniteClient-Win64-Shipping_BE.exe
Searching PID 15492 ...
Processed 51.34 MB, speed = 1.60 MB/s
Done!"

but where does it export the actual aes key?

**Comment by battledash** [comment]
sorry for chat walling :P

**Comment by battledash** [comment]
the whole reason im doing this is because no one is leaking the fortnite aes keys for uModel and the encrypted pak files, I've seen people leak them before but a while ago and im assuming they have to be pulling them from proccess memory as this is the only solution I could find. do you know of any programs that its sure to have aes keys for just to make sure mine is working as it should?

**Comment by mmozeiko** [comment]
> try it on chrome I get this:

Did you build binary as 64-bit? From readme:

> 32-bit binary can search only in 32-bit processes, 64-bit binary can search in both - 32 and 64-bit ones

> but where does it export the actual aes key?

It prints out found keys to stdout, just like shown on readme.

Fortnite won't work at all because it uses anti-debug features - it prevents reading memory from other processes (see #7). If you write extra code to circumvent that, then aes-finder will work fine.

**Comment by battledash** [comment]
Im compiling it as Release x64 and still same errors with chrome
where is stdout?

**Comment by battledash** [comment]
would anti-anti-debuggers work for it like ScyllaHide?
https://github.com/nihilus/ScyllaHide

**Comment by mmozeiko** [comment]
stdout is what you seen in console.

No idea about ScyllaHide. I have not used it, and I have no idea how Fortnite is doing its anti-debug.

**Comment by battledash** [comment]
just looked back on fortnite after trying the exe again and got this:
https://imgur.com/a/hpItuz5

**Comment by battledash** [comment]
oops
