### ISSUE TITLE
Please provice high level overview of how&why this programme works

### ISSUE THREAD

**Issue by pd211** [mmozeiko/aes-finder#12]
Hi! AES noob here
Please give a high level overview of how&why this programme works. 
Why is it using the AES MixColumn matrix to find a key?
Why it is checking memory in normal and reverse order?
Thanks so much for helping !

**Comment by mmozeiko** [comment]
It searches for expanded key schedule of AES. Typically when you have 16-byte key (for AES-128) then to actually use it you expand it to 44 bytes. Rest of 32 bytes are calculated in with algorithm explained here: https://en.wikipedia.org/wiki/Rijndael_key_schedule

This means we can do following:
* we analyze every 44 byte region in memory
* we take first 16 bytes, do AES key schedule algorithm
* then compare last result of it with last 32 bytes in memory region 32 bytes
    * If they match, this means we have found key (first 16 bytes).

Similar process works also with AES-192 and AES-256. You can apply same technique with other block ciphers, as long as they have similar concept of key scheduling.

As to why search memory in reverse order - I've seen some AES implementations that keep bytes in memory in reversed order. It is not really needed to find keys in normal AES libraries, but to be 100% sure I find keys for these reversed-storage AES implementations, I also search bytes in reversed order.

**Comment by pd211** [comment]
Thank you @mmozeiko !
