### ISSUE TITLE
Proccessed 0.00MB, speed = 0.00 MB/s

### ISSUE THREAD

**Issue by Frosty704** [mmozeiko/aes-finder#13]
Running the aes finder on Fortnite and it says "Proccessed 0.00MB, speed = 0.00 MB/s". Although, I try running it on another program like Chrome and it finds the encryption keys.
![image](https://user-images.githubusercontent.com/36753686/48553738-63b9b780-e8aa-11e8-871f-78467e1c0af2.png)

**Comment by mmozeiko** [comment]
See discussion in #10 why this happens with Fortnite process.
Technically aesfinder can find keys in Fortnite, but you'll need to write some extra code to prevent anti-debug features in Fortnite.

**Comment by Frosty704** [comment]
> See discussion in #10 why this happens with Fortnite process.
> Technically aesfinder can find keys in Fortnite, but you'll need to write some extra code to prevent anti-debug features in Fortnite.

Where would I write this code and what would it be?

**Comment by mmozeiko** [comment]
That depends on actual anti-debug/tamper protections Fortnite uses. I don't know that as I have not analyzed it.

Here are a few popular examples, but in no way these are a comprehensive reference:
http://pferrie.host22.com/papers/antidebug.pdf
https://www.secnews.pl/wp-content/uploads/2011/05/whitepaper_antidebugging.pdf

There are many different ways how these protections could be implemented. You'll need to use disassembler/debugger (IDA/OllyDbg/x64dbg) to analyze what Fortnite uses and how to work around it. After that you'll be able to run run aes-finder on it.

**Comment by Frosty704** [comment]
Thanks, i got it to work
It's just that it threatens to ban me if I don't close the anti anti debugger and aes finder

**Comment by mmozeiko** [comment]
Could you post the steps you did to get it working? So if somebody else has similar issue and founds this topic they can read the solution.

**Comment by Frosty704** [comment]
1. Downloaded ScyllaHide
https://github.com/x64dbg/ScyllaHide/releases
2. Put InjectorCLIx64.exe into Release>NtApiTool>x64
3. Ran PDBReaderx64.exe
4. Opened Fortnite(or whatever you're needing to do this for)
5. Injected ScyllaHide via InjectorCLIx64.exe
6. Used aes-finder as normal

**Comment by Sam54123** [comment]
what's this InjectorCLIx64.exe that you're talking about?

**Comment by Igrium** [comment]
How do I get the dll path InjectorCLIx64.exe  requires?

**Comment by mmozeiko** [comment]
@savageduckerino Thank you!

@Sam54123 If I read ScyllaHide pdf documentation right, you simply put path to `HookLibrary.dll` file. Check the pdf for more detailed instructions.

@BattleDashLeaks fyi, if this is still relevant to you.
