### ISSUE TITLE
Does not detect 8 byte AES keys

### ISSUE THREAD

**Issue by ZirakC** [mmozeiko/aes-finder#14]
Hello,

I have noticed that the application only supports extracting AES Keys based on 4 bytes (x256) from the "TE" variable.

In the application I am trying to extract the keys from, it seems like it uses a slightly different table:
0xc6636300, 0xc66363a5, 0xf87c7c00, 0xf87c7c84, 0xee777700, 0xee777799, 0xf67b7b00, 0xf67b7b8d,
	0xfff2f200, 0xfff2f20d, 0xd66b6b00, 0xd66b6bbd etc.

As you can see, it seems to be an 8 byte table (correct me if I'm wrong). You can see the entire table found here under "aes$Te"

https://2ton.com.au/library_as_html/aes.inc.html

Is it possible to incorporate this aes TD/TE tables in attempting to extract the keys? I believe that's why it may not be able to detect it.

I've been trying to gather as much information as I could about this table, and based on this link, it seems to be an "8 byte aligned 2048 table":
https://cr.yp.to/mac/aes_big_constants.c

Would appreciate it if someone could guide me to the right direction, and could assist in what I may need to implement to support reading this table? Or if someone already have implemented this feature in their copy, if they could contribute it to this project?

Regards,
Zirak

**Comment by mmozeiko** [comment]
Not sure why this library does this but TE/TD tables are two times larger where every even index element is not used at all. Every odd index element is same as my/standard TE table. Check their aes$Te table with index 1, 3, 5, 7, ... and you'll see it has exactly same elements as my TE table.

And if you see how aes$Te table is accessed, it is always reading [index*2+1] elements (where index is 0..255 byte). See following instructions:

    xor	a, [aes$Te+rax*8+ ((6-3) mod 4) + 1]
    movzx	ecx, byte [aes$Te+rax*8+1]

Maybe they are doing to prevent cache time attacks? I'm not sure..

That said, my code still should find keys from their key expansion as long as they store them in same format. Key expansion / keygen does not use TE/TD tables, so they do not matter. They are in my code only to speed up finding.
 
How does their algorithm store expanded keys? Can you compare it with standard algorithm. Call their keygen and compare output with normal aes key expansion. How do they differ?

**Comment by ZirakC** [comment]
Hi mmozeiko,

Thanks for your input on this. Unfortunately this application is virtualized, however, I was able to scan the memory and locate this AES table within the application's main module, which leads me to believe that it utilizes AES 256 bit encryption.

I am trying to understand why it wouldn't pick up the encryption key from a simple scan, is it possible that the key may be stored in a way that's not aligned by 4 bytes? (e.g. starts at 0x0001 as the offset?) I am thinking maybe this application scans every 16 bytes (/44 bytes), and then jumps to the next 16 bytes, without traversing each byte individually to identify whether it is an AES encryption key.

Again, thank you very much for your time and effort on assisting me.

**Comment by mmozeiko** [comment]
That does not matter what application is. You simply create new executable that you can run. Include aes.inc file and call key expansion to check in debugger what does it return. Then compare it with normal aes key expansion. 

Based on these results it should be pretty obvious what is the difference and how to fix it. I don't have time to look at aes.inc code, but my guess would be on byte-order. Maybe it is doing something fancy - storing key in normal order, but rest of expanded key in reversed order? Or vice-versa. Or something similar.

Currently aes-finder assumes that expanded key is stored as 4-byte integer array where each element is either little-endian or big-endian. But all of them must be with same endianess. This is pretty much what all crypo libraries do. Maybe this one is very special. Maybe this expanded array has extra padding between elements or different data interleaved. Fix for this is super easy, just need to figure out what does it do differently.

**Comment by ZirakC** [comment]
Ahh I see. I will need to take a look tomorrow. I appreciate your assistance on this, thank you.

**Comment by ZirakC** [comment]
I'm starting to think maybe due to how VMProtect virtualizes the assembly instructions, it may in a way obfuscate the way the key is stored/read. Have you ever come across something like that before?

**Comment by mmozeiko** [comment]
I don't now how VMProtect works, but if it changes only instructions - that does not matter. As long as data in memory is put in same way - meaning order is the same, and values are the same (not scrambled), then the key can be found.

**Comment by ZirakC** [comment]
I'm comparing dumps of the memory (before it uses any form of AES encryption, and after it's used), I can see the AES table gets populated in the second dump, I'm going to dig further to see if I can manually spot the key somehow getting populated as well.

I've attached my dumps if you were curious to see what it looked like (just do a binary compare).

[mem.zip](https://github.com/mmozeiko/aes-finder/files/2660968/mem.zip)

Edit:

Upon further inspection, it appears to use Crypto++ library
Edit 2:
Continuing to dig into the Crypto++ Library, seems to be using Rjindael.cpp, as you can see it fills the Enc/Dec table on runtime using FillEncTable() and FillDecTable() based on the "Se" and "Sd" variables, which is identical to what we have defined as "Te" and "Td" variables in this aes-finder project.

Now I'm wondering if its possible to merge the Crypto++ AES portion of the library into this project, seems like a huge task to do, but might make it all the more worthwhile if it adds more support.

Also, the "Te" table (equivalent to the "TE" table in the AES-Finder project) is an array of 64 bit values with the size of 256 + 2.
`namespace rdtable {CRYPTOPP_ALIGN_DATA(16) word64 Te[256+2];}`

**Comment by ZirakC** [comment]
I ran the Crypto++ test program to test Rijndael (command line param: v 44) and then ran AES-Finder on it, and it seems like it wasn't able to find the key, even though I can directly scan the memory for it:

![image](https://user-images.githubusercontent.com/10685608/49703431-04ae4080-fbd3-11e8-9495-66b5f52aa596.png)

The circled area in the following image is where it's printing the output for cryptest.exe

![image](https://user-images.githubusercontent.com/10685608/49703455-3fb07400-fbd3-11e8-8212-edc3ec51847b.png)

Also, this is the data set in the valdata variable:

![image](https://user-images.githubusercontent.com/10685608/49703491-c7967e00-fbd3-11e8-843c-2b8d44b37377.png)


For Reference, this is the Crypto++ library I downloaded for my test:
https://www.cryptopp.com/cryptopp700.zip

**Comment by ZirakC** [comment]
Based on further debugging from aes-finder, it seems like it reads the key and then 224 bytes (after the key's 32 bytes). Is it possible the application I'm trying to find the AES Key for doesn't have the data after the key (or just stores the plain 16 bytes and cipher 16 bytes = 32 bytes?)

**Comment by mmozeiko** [comment]
aes-finder expects key to be stored in expanded form as a array of 16-byte elements. Count of elements in array is how many rounds you need - 11 for AES-128, 13 for AES-192, 15 for AES-256. That means this array size in bytes for AES-128 it is 11\*16 =176 bytes. For AES-192 it is 13\*16 = 208 bytes. For AES-256 it is 15\*16 = 240 bytes. And because how AES rounds work - for encryption the actual key is in first 16/24/32 bytes of array, but for decryption key is in last 16/24/32 bytes of array.

If application stores this data differently, then aes-finder won't work. You need to check how exactly it stores expanded key and adjust the code so it compares expanded round keys correctly.

For example, I have seen application to do key expansion on the fly. That is - it does not store expanded keys, just the original one. And then for each round of encryption it does expansion process. This is OK if all you want to encrypt is one block. For many blocks this will be not efficient - that's why most of applications expand the original key to expanded key.

**Comment by ZirakC** [comment]
Thinking outside the box now, what if I have the encrypted data, could I simply scan throughout the memory and for each 32 bytes I read, I pass it on to an AES Decryption function with the encrypted data, and see which set of 32 bytes decrypts to plaintext successfully? The only question in that case would be how to get the IV key..

**Comment by mmozeiko** [comment]
That is a bit different problem you are solving. aes-finder finds the key, not the encrypted data.

Doing what you suggesting (calling decryption function) means that you already have the decryption key in some form - either expanded one (240 bytes for AES-256), or actual key (32-bytes for AES-256). There is no need to use aes-finder at all.

IV is not a key. It is not secret. It is typically prepended to encrypted data and sent together with it. Sometimes it is in separate field. But it is always available in plain format if you have access to encrypted data.

**Comment by ZirakC** [comment]
Sorry, to clarify. I don't have the key, however, I try to guess the key by reading every sequence of 32 bytes from the memory of the application, and call a standard AES decryption function with that key on the encrypted data I already have, and then check the result to see whether the data successfully decrypted to plain text.

If it successfully decrypted, then we would know the random 32 bytes I read from the application would be the key, correct?

**Comment by mmozeiko** [comment]
Ah, I see. Yes, that would work.

But I would be surprised if the app does not use aes expanded key in some form. Just need to understand format and update aes-finder to detect it. And it will find the key.

**Comment by ZirakC** [comment]
Based on your earlier comment
"And because how AES rounds work - for encryption the actual key is in first 16/24/32 bytes of array, but for decryption key is in last 16/24/32 bytes of array."

Would this mean that even the expanded form would still have the original 32 bytes for the encryption key (is the first 32 bytes = to the key that is not expanded)? Is the expanded form merely used for validating that the key is correct? Sorry, I'm new to any types of encryption :)

Just trying to see if my method that I mentioned would work in the event it actually stores the expanded key. If I can brute force my way of finding the key this way, I can dump the actual memory of where it's stored to see why  aes-finder didn't pick it up.

**Comment by mmozeiko** [comment]
Yes! Exactly. That's how it works. That's why aes-finder simply prints out first N bytes (or last N) if all other bytes match to expanded key.

See an example here: https://github.com/kokke/tiny-AES-c/blob/master/aes.c#L152
First thing it does is to copy key (`Key` argument) into first N bytes of expanded key (`RoundKey` array). All other RoundKey elements are derived from these first N bytes. Where N is 16/24/32 - key size in bytes.

Same thing in in OpenSSL: https://github.com/openssl/openssl/blob/master/crypto/aes/aes_core.c#L654

For decryption the expanded key is in reversed order - actual key goes last in the memory. And for other rounds it does few extra transformations.

**Comment by ZirakC** [comment]
I'm perplexed at this point, I've tried brute forcing based on the memory dump of the application, but nothing I decrypt comes out readable. I'm reading the first 16 bytes as the IV from the encrypted data, and am using that across all my decryption calls based on 32 bytes of memory read from each section of the memory. Maybe I'll try reducing the key size to 16 bytes, and then try 24 bytes...

![image](https://user-images.githubusercontent.com/10685608/50048225-5738a280-0094-11e9-8f95-be3238286e07.png)

**Comment by ZirakC** [comment]
I was able to detour the winhttp DLL and hooked the WinHttpReadData function and put a messagebox.

If I scan the memory while the message box is open on WinHttpReadData, I can see the AES 256 bit keys (two sets of keys, e.g.:
[001646EC] Found AES-256 encryption key: b7f75efb57789727924287fd99001cbbdfafaef36746d03f99f7b78dec3927c4
[001647CC] Found AES-256 decryption key: b7f75efb57789727924287fd99001cbbdfafaef36746d03f99f7b78dec3927c4
[00169A6C] Found AES-256 encryption key: 0009be7804838449a1b688ba411803c086e28d008470fcd6e3bf1b6d8a115653
[00169B4C] Found AES-256 decryption key: 0009be7804838449a1b688ba411803c086e28d008470fcd6e3bf1b6d8a115653
)

However, for each WinHttpReadData request, the key changes.. is that normal?

**Comment by mmozeiko** [comment]
If it is an https URL then yes, it is normal. Each https connection should use different session key. If it is not https, then who knows what winhttp is doing internally...
