### ISSUE TITLE
When Ran with Local Debug I Get [C4456] & the Built Program doesnt Run

### ISSUE THREAD

**Issue by FenrirLupus** [mmozeiko/aes-finder#15]
Hello I am Using VS 2017 & I retargeted the Solution and chose the Right Toolset but still cant build the solution
[C2220] Warning Treated as Error -No 'Object' File Generated

Please Help.

1- Ok I got it to Build Correctly but now no .exe or anything is created nvmd an .exe is created in
aes-finder-master\msvc2013\x64\Debug but when i run it no window do i have to run it in cmd?

2- Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4456	declaration of 'len' hides previous local declaration	aes-finder	d:\[downloads]\aes-finder-master\aes-finder.cpp	981	
I get this Now

**Comment by dem0nk1d** [comment]
I see the application will latch onto the binary being called at the command line, but how can we use this application to attach to other processes being called by the main binary?  Will dll files be scanned as well?

**Comment by mmozeiko** [comment]
Not in form as code is currently. But you can call it directly on child process. Dll or exe files doesn't matter. Program scans whole process memory, regardless from where it was allocated.
