### ISSUE TITLE
Noob on how to use

### ISSUE THREAD

**Issue by ghost** [mmozeiko/aes-finder#17]
Maybe i do not have enough coding experience to understand what i need to do but i am trying to test it on an encrypted exe file that i made just to see if it can guess the AES key. To be honest i tried following the README but i still have no clue what i am looking for when it talked about using the aes-finder.exe. I have no clue how that is created or where it would be. Help is much appreciated.

**Comment by mmozeiko** [comment]
This program searches for key in process memory. It will find it only if process keeps AES key in expanded format. If key is expanded only for a moment and then overwritten, it will not find the key.
You get aes-finder.exe by compiling code with Visual Studio or gcc/clang C++ compiler.
