### ISSUE TITLE
Keys seem too long. 64 length instead of 32

### ISSUE THREAD

**Issue by evan25lee** [mmozeiko/aes-finder#18]
I'm attempting to try and get the AES keys from the BDS (Minecraft bedrock editions official dedicated server). I ran the command and got a list of 18 keys that say they are for AES-256. However the results I got were 64 characters instead of 32 characters. Now, this tool may not even be what i'm looking for. What i'm attempting to do is get the keys so I can decrypt packets going into the server. I already have a method of catching the packets its just the decrypting that i'm stuck on.

**Comment by mmozeiko** [comment]
AES-256 key is 32 bytes long. One byte represents value from 0 to 255. In hex that is 00 to ff. So each byte is two hex characters. 32*2 = 64 hex characters.

**Comment by evan25lee** [comment]
Ah, didn't realise they were in bed. Thanks
