### ISSUE TITLE
Simple code bug.

### ISSUE THREAD

**Issue by moogamouth** [mmozeiko/aes-finder#19]
Hi. Ran the code in vs, and got an error: 1>C:\Users\Isaac Weingrad\Downloads\aes-finder-master\aes-finder-master\aes-finder.cpp(981): error C2220: the following warning is treated as an error
1>C:\Users\Isaac Weingrad\Downloads\aes-finder-master\aes-finder-master\aes-finder.cpp(981): warning C4456: declaration of 'len' hides previous local declaration
1>C:\Users\Isaac Weingrad\Downloads\aes-finder-master\aes-finder-master\aes-finder.cpp(969): note: see declaration of 'len'.

**Comment by mmozeiko** [comment]
Code was written for Visual Studio which probably is much older than you are using. Feel free to fix warnings, so they do not happen, then it should work fine.

**Comment by moogamouth** [comment]
Ok, thank you very much. I converted it to a new version, so yeah. I tried fixing it by replacing `else if (int len = aes_detect_dec((const uint32_t*)&buffer[offset], key))` with `else if (int (len == aes_detect_dec((const uint32_t*)&buffer[offset], key)))`, and I opened up the application it compiled to, but it ended immediately. I don't know what to do.
