### ISSUE TITLE
Is there a log saved anywhere?

### ISSUE THREAD

**Issue by SethTooQuick** [mmozeiko/aes-finder#20]
It took a second, but I want to know if it saves a log. It closed automatically, but luckily I saved a screenshot of before it finished. Does it save a log of the keys it found?

**Comment by mmozeiko** [comment]
It outputs everything it finds to standard output. Either run everything in command-line. Or redirect output to file.

**Comment by SethTooQuick** [comment]
Hey thanks, I ended up just typing out all of them from the image, but in the end none of them worked lol. Trying to check out files from the Minecraft Dungeons beta and to open the paks you need the AES keys.
Anyway, how would you go about running this in the command line?

**Comment by SethTooQuick** [comment]
I'm surprised I was even able to get the thing to build, never in my life have I compiled something.
