### ISSUE TITLE
When I run it says Failed to open process.

### ISSUE THREAD

**Issue by OneGuyGames** [mmozeiko/aes-finder#22]
Trying to find the AES key to Valorant but when I do i get 

Searching PID 7072 ...
Failed to open process.
Done!

**Comment by mmozeiko** [comment]
Probably anti-debug or something similar prevents accessing process memory.
This tool works only when target process does not do any anti-debug/anti-cheat measures.
See #10 and #13 for similar issue.

**Comment by subsr97** [comment]
If you're on Linux, you should be running aes-finder as root.

**Comment by mmozeiko** [comment]
@subsr97 OP mentioned he's using it on Valorant. I don't think Valorant is released on Linux.

**Comment by elsamuko** [comment]
If the target process is running as **64 Bit**, but aes-finder was compiled as **32 Bit**, it cannot open the target process.

**Comment by Numenorean** [comment]
Run as an admin
