### ISSUE TITLE
Need Help with AES

### ISSUE THREAD

**Issue by Qertat** [mmozeiko/aes-finder#31]
Can you make your tool compatible with pubg mobile ( V1.6 ) I am looking for key for the game attaching link of apk if somehow you can help. I cannot locate shipping .exe for mobile games.
https://web.gpubgm.com/m/AOS_Beta1.6.0-b.4_No7_1.6.3.15430_Shipping_Google_CE.shell.signed.apk

**Comment by halloweeks** [comment]
I try this found pubg mobile AES key
Check: https://github.com/halloweeks/pubg-mobile-aes-keys/blob/main/README.md

**Comment by halloweeks** [comment]
> Can you make your tool compatible with pubg mobile ( V1.6 ) I am looking for key for the game attaching link of apk if somehow you can help. I cannot locate shipping .exe for mobile games. https://web.gpubgm.com/m/AOS_Beta1.6.0-b.4_No7_1.6.3.15430_Shipping_Google_CE.shell.signed.apk



> Can you make your tool compatible with pubg mobile ( V1.6 ) I am looking for key for the game attaching link of apk if somehow you can help. I cannot locate shipping .exe for mobile games. https://web.gpubgm.com/m/AOS_Beta1.6.0-b.4_No7_1.6.3.15430_Shipping_Google_CE.shell.signed.apk

I found pubg mobile AES key
Check: https://github.com/halloweeks/pubg-mobile-aes-keys/blob/main/README.md

**Comment by halloweeks** [comment]
pubg mobile pak index offset and index size is also encrypted with xor
