### ISSUE TITLE
finding ssl keys

### ISSUE THREAD

**Issue by spm201** [mmozeiko/aes-finder#4]
I  have run aeskeyfins with different browswers and I am finding 128-bit as well as 256-bit keys. Are these

keys used in ssl protocol. If Yes then how can they be ecure enough to be used,

**Comment by mmozeiko** [comment]
Yes, some of the keys are probably TLS session keys. I have tried this on putty and it definitively finds SSH session AES-keys.

You must understand that if attacker can run any kind of software on your machine (like this aes-finder) then it's already too late. He could be running password logger or grab screenshot and send to his machine. Or he could be running ransomware and encrypt all of your files. Or simply uploading all your files (including browser history/cookies/email-content) to his server. There's no need to find AES keys in memory for that.

**Comment by sanchit3008** [comment]
Aes-finder with browsers gives some interesting results. It seems legit that it finds some TLS session keys when a website with a secure channel is being surfed, but sometimes upon opening websites without a secure connection too I get some keys. Also, does aes-finder work with combination encryption schemes - like AES-Twofish?

**Comment by mmozeiko** [comment]
Yes, it should find AES key from AES-Twofish and similar combinations. It should also be possible to write an algorithm that will find Twofish or other block cipher keys in similar manner - by searching for expanded keys.
