### ISSUE TITLE
Request for Detailed Explanation of AES Finder Tool's Functionality

### ISSUE THREAD

**Issue by halloweeks** [mmozeiko/aes-finder#40]
Hi there,

I came across your AES Finder tool on GitHub, and I find it intriguing. I'm particularly interested in understanding how the tool operates in detail. Could you please provide a comprehensive explanation of its functionality? Specifically, I'm curious about:

1. **Operating Principle:** How does the AES Finder tool locate and extract AES keys from memory processes at runtime?
2. **Supported Key Lengths:** You mentioned that the tool extracts AES keys of lengths 128, 192, and 256 bits. Could you elaborate on how it distinguishes between these key lengths during extraction?
3. **Encryption/Decryption Keys:** You also mentioned that the tool extracts encryption and decryption keys. Can you explain how it identifies and extracts these keys?

A detailed explanation would not only enhance my understanding but also help other users grasp the tool's capabilities better.

Looking forward to your insights!

Best regards,
halloweeks

**Comment by mmozeiko** [comment]
When AES encryption/decryption runs, it typically uses expanded key, which is stored in memory for performance reasons, not calculated on the fly. So you don't need to perform same key expansion over and over again for each block you encrypt/decrypt. See section `5.2 Key Expansion` in AES standard: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf

These bytes for expanded key are derived in specific way from original 16/24/32 byte AES key. That means we can check each block of X bytes (11*16 bytes for AES-128, 13*16 for AES-192 and 15*16 for AES-256) do they match expanded key bytes from initial 16/24/32 bytes (initial bytes for first round always is AES key). If they match - we have found the key, and you know the AES size 128/192/256 depending on for which AES the expanded key matches.

As to how encryption vs decryption key is differentiated - optimized AES decryption implementation uses differently expanded key. You can check expanded key for matching to decryption expansion, and if it matches then this AES key is used only for decryption. But if the tool prints out that key is "encryption" that does not mean implementation does not use it for decryption. It might, it just means the decryption implementation of AES in program is not optimized.

And all this works only if implementation uses AES implementation that stores expanded key in memory. If AES implementation is very customized that does not store this expanded key in array, then my tool won't find any keys.


 See

**Comment by halloweeks** [comment]
how it determines the correct order of data for AES algorithms that store round keys differently in memory. Some AES algorithms store round keys in reverse order, while others use byte order.

**Comment by mmozeiko** [comment]
It tries both orders - forward and backward.

**Comment by halloweeks** [comment]
Thanks for information!
