### ISSUE TITLE
Cannot run on Mac M1/ARM64

### ISSUE THREAD

**Issue by hermanocabral** [mmozeiko/aes-finder#44]
Hello,

I've used this tool in the past on Intel Macs but now I'm experiencing a lot of issues when trying to run this on a M1 Mac. Does this work on ARM?

**Comment by mmozeiko** [comment]
Yes it works. There's really nothing special you need to do. Just compile it and it will run fine.

**Comment by hermanocabral** [comment]
Using ```Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix``` with -03 gives me this ```Self-test aes192_detect_decF<true>(aes192_decBF) failed``` error and without it gives all different sorts of errors when trying to open the process.

I'll try using GNU GCC.

Thanks!

**Comment by mmozeiko** [comment]
Try to replace `return (x >> n) | (x << (32 - n));` line with `__builtin_rotateright32(x, n);` Sometimes higher level optimization levels in clang optimizes this a bit wrong.

**Comment by hermanocabral** [comment]
No bueno, without the optimizations I've got an error when calling `task_for_pid` here:

```
static bool os_process_begin(uint32_t pid)
{
    mach_task_self()
    kern_return_t kr = task_for_pid(mach_task_self(), pid, &os_process_task);

    if (kr != KERN_SUCCESS)
    {
        return false;
    }

    os_process_addr = 0;
    os_process_size = 0;

    return true;
}
```

On My Machine™ I managed to get it working by re-signing the binary with the `com.apple.security.get-task-allow` entitlement. It seems recent versions of MacOS have been restricting the usage of task_for_pid.

**Comment by mmozeiko** [comment]
Yes, newer mac's will require either resigning exe, or probably by disabling SIP. I'm not distributing macos executables so it's up to you to sign it.
