### ISSUE TITLE
Dumb question ? What about IV or Counter ?

### ISSUE THREAD

**Issue by Arno0x** [mmozeiko/aes-finder#6]
Hi,

Sorry if my question is dumb: what can you do with an AES key if you don't have the IV or counter that was used for encryption ?

Cheers

**Comment by mmozeiko** [comment]
Typically encrypted streams have IV available somewhere in protocol.

For example it is very common for CBC encrypted data to be stored/transmitted like this:
`[IV] [block0] [block1] ... [blockN]`
So all you need is a key, afterwards you can decrypt the data.

Sometimes you don't need IV at all, for example, ECB mode.

**Comment by Arno0x** [comment]
Ok, I get the point. Thank you ! (I hope ECB is not used anywhere anymore :-) )
