### ISSUE TITLE
Can't compile in vs2017

### ISSUE THREAD

**Issue by battledash** [mmozeiko/aes-finder#8]
Im trying to compile it in visual studio 2017 using v120 build tools and 8.1 sdk

When I click "Local Windows Debugger" I get an error that the exe isn't there
shouldn't it be creating the exe?
I cant find a fix anywhere
Please respond

**Comment by mmozeiko** [comment]
Please show the contents of Output window when doing build.

**Comment by JaydenMaalouf** [comment]
I think you'll find you're sadly mistaken. Turn warning levels down to Level 1, retarget your SDK and you're fine to go. Successfully compiled and working like a charm
